### PR TITLE
Create virtual 4C tool

### PR DESCRIPTION
**Pull request by Phlya**
API and CLI for virtual 4C.
No support for expected (for now?).

### CODE REVIEW

**Comment by Phlya** [comment]
Example how to use. Notice that using a viewpoint larger than binsize averages all bins within it, and masks out interactions inside the viewpoint.
Screenshot 2022-08-19 at 11 02 28

**Review by gfudenberg — COMMENTED** [review]
nice! 
Couple q's:
- would it make sense to add an option to smooth via https://github.com/open2c/cooltools/blob/51cc542365aedb8776d7fde1de1e8cd8d687b723/cooltools/lib/numutils.py#L994
- should this go through sandbox first?

**Comment by Phlya** [comment]
Can try to see what smoothing does to this! But I'm not sure there really is a reason to smooth this, idk...

Don't mind putting into sandbox first!

**Comment by Phlya** [comment]
For sandbox, is there a way to make the CLI accessible somehow?..

**Comment by Phlya** [comment]
For CLI tests to pass I had to add an empty `return` int he end and assert that exit code==0, not ==1, any idea why? Otherwise the code was 2. In geneal, some of out tests assert code==0, and some==1. Why is that?

**Comment by agalitsyna** [comment]
Exit codes seems like a serious issue, e.g. see here (exit_code==1, but not 0 for no reason): https://github.com/open2c/cooltools/blob/a86fbec9601459624568f7f03c6ec89d445ca416/tests/test_insulation.py#L23

**_This is dangerous for the tests_**, because if it's actual mistake it can also naturally have exit_code 1 and it will be never captured by our tests. 

One of the ways to debug it is to output stderr and stdout alongside with exit_code while creating tests: https://github.com/pallets/click/issues/737

**Comment by Phlya** [comment]
I think in this case it's not an issue, since with an empty return statement at the end the code is 0. And I assume if there is an actual error it won't get to the return statement and will give an error-y code. So perhaps this should be a broader discussion in a separate issue? @agalitsyna

**Comment by Phlya** [comment]
@gfudenberg added a note that it's new and experimental, do you think it's enough?

**Comment by gfudenberg** [comment]
sounds good!

one question though: would these functions make more sense as part of cooler, if they don't modify/process in any way other than querying/balancing ?
cc @nvictus

**Comment by Phlya** [comment]
It's also averaging bins within the viewpoint...

**Comment by gfudenberg** [comment]
indeed!

**Comment by Phlya** [comment]
@gfudenberg any more comments?

**Comment by gfudenberg** [comment]
nope!

**Comment by Phlya** [comment]
Ok to merge?

**Comment by gfudenberg** [comment]
fine by me!

**Pull request merged**
