### PR TITLE
add expected test, make saddle tests pass

### PR DESCRIPTION
**Pull request by sergpolly**
keep cleaning after the expected update ...

now just resolved the compatibility between current output of cli expected and whatever compute-saddle wants it to be (added `--regions` option to saddle, but it's not 100% functional yet)

also added a simple cli compute-expected test...

tests should pass now

### CODE REVIEW

**Comment by sergpolly** [comment]
oh no - wtheck ?
```
Processing dependencies for cooltools==0.4.0.dev0
error: cytoolz 0.11.0 is installed but cytoolz<0.11 is required by {'cooler'}
```

**Comment by nvictus** [comment]
I had to introduce `cytools<0.11` for Python 2.7 in the last 0.8 release. I'll remove the restriction in cooler 0.9.

**Comment by sergpolly** [comment]
> I had to introduce `cytools<0.11` for Python 2.7 in the last 0.8 release. I'll remove the restriction in cooler 0.9.

Oops - so - was it bad that I've removed cytoolz from cooltools requirements ? Or it is fine - since cooler pulls it anyway ?

**Comment by nvictus** [comment]
It's fine if it's causing conflicts like that. We can re-introduce it later.

**Pull request merged**
