### PR TITLE
enable smooth and aggregate in cis-expected using Antons smoothing

### PR DESCRIPTION
**Pull request by sergpolly**
@golobor check this out - does this align with your vision ?
this is a bit quick and dirty , but Im not sure there is much more to it ...
I kept diffs as small as possible, to allow quicker review

if that looks ok - we can sandbox logbin

### CODE REVIEW

**Comment by sergpolly** [comment]
have to admit - it was super easy ! - didn't not check how the results look like though

1 thing we should do is to prevent your function to dump _ALL_ of the additional columns ... maybe ...

**Comment by golobor** [comment]
wow, looks good! i think it should do, for now - but could you also add an extra-flag for sigma_log10 , which defines the width of the smoothing kernel in the log10 space?

**Comment by sergpolly** [comment]
@golobor  - what bout `window_sigma` ? it looks like it is also responsible for the width of smoothing ...

**Comment by golobor** [comment]
oh, sorry, window_sigma is a technical parameter. the choice of the name is probably confusing - may be we can dedicate one of our post-release calls to this algorithm

**Comment by Phlya** [comment]
We already dedicated this call to this algorithm :D See the comment in #280 for a suggested change to the API.

**Pull request merged**
