### PR TITLE
cool_cis_eig: added bad_bins and docstring

### PR DESCRIPTION
**Pull request by sergpolly**
added `bad_bins` for quick masking (e.g. small translocations and such), added docstring, changed a couple of variable names - to make more readable

@mimakaev this should be small and innocent, could you check please ?

### CODE REVIEW

**Comment by mimakaev** [comment]
Looks like it's good to merge... I didn't look at merge conflicts - can try to resolve tomorrow.

**Comment by sergpolly** [comment]
i looked at conflicts, and realized that your version of eigdecomp/cooler_cis_eig (the one you've updated to be based on `parse_regions`, and the one I was working with) somehow disappeared in the middle of this huge squashed commit: https://github.com/open2c/cooltools/commit/a0ee39d028f6525c0b4e96bbe5248e5b2d8527d6#diff-e446d8028b332795daa93c83224f383399eb0fde5d53d8624049449d96aa6495

So whatever is in current master/develop of cooltools is "old" - pre bioframe update , or at least pre `bioframe.parse_regions`

I don't really understand how that happened, but I think I managed to reconstruct your version of it, and simple compartment calling test is passing now (no regions, only full chromosomes)...

If you look at the diffs of this commit - do you remember what was the deal here ? why there were these `subregion` `subindex` calculations , as opposed to several bioframe operations in the old (and current) version ?

**Comment by sergpolly** [comment]
You can see how the version is changing around these commits in develop-branch:
https://github.com/open2c/cooltools/commit/8687c8a4b7eaff9ee371d0a415a7dddc5206a499
https://github.com/open2c/cooltools/commit/c4a8180e1101e248314496ed7c13ea89bd887ef8

it's a bit crazy - I guess we shouldn't be squashing huge PRs going further - smaller incremental steps are easier to track and understand

**Comment by sergpolly** [comment]
close in favor of  "clean" develop

**Pull request closed without merging**
