### PR TITLE
Scaling plot

### PR DESCRIPTION
**Pull request by DekkerBastiaan**
Added scaling script using pairix for fast random access.

### CODE REVIEW

**Comment by sergpolly** [comment]
We see so many commits here, likely because the `develop` branch is not up to date with `master` (needs to be updated anyways) - the scaling script itself is just a couple of commits at the very bottom.

**Comment by golobor** [comment]
awesome, thank you!! I'll take a look

**Comment by Phlya** [comment]
Just wanted to mention that output of `pairtools stats` contains all required information to make a scaling plot, so, for example, for distiller-analysed data a separate script might be redundant - but I'm travelling and haven't actually checked what this script is doing. And maybe this is useful anyway.

**Comment by sergpolly** [comment]
pairs-related scripts have been moved to https://github.com/open2c/pairlib - so this no long applies

**Pull request closed without merging**
