### PR TITLE
Symmetrize on-diagonal pileups correctly

### PR DESCRIPTION
**Pull request by Phlya**
Fixes https://github.com/open2c/cooltools/issues/406
And addresses comments from https://github.com/open2c/cooltools/pull/418, and supersedes it.
(except the idea for a test for correct symmetrization... but np.fmax seems foolproof!)

### CODE REVIEW

**Comment by golobor** [comment]
hmm, @Phlya , are you sure that the lower triangle is filled with zeros and not nans?
@sonkoles29 and I just tested your code and it gave us all nans. Upon step-by-step debugging, we found that the variable stack in snipping.py:987 seems to have its lower triangle filled with nans...

**Comment by Phlya** [comment]
You are right @golobor ! Not sure what happened yesterday... Anyway, try the new commit?

**Comment by Phlya** [comment]
@golobor @sonkoles29 is this ok to merge in your opinion?

**Review by gfudenberg — APPROVED** [review]
looks good!


should add one test for bedpe type pileup that asserts that everything below the diagonal is np.nan

**Review by golobor — APPROVED** [review]

**Pull request merged**
